name: PR feedback comment

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

concurrency: # Only one job per PR at a time
  group: pr-${{ github.event.pull_request.number }}-c
  cancel-in-progress: true

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  wait-for-worklows: # Wait for the other workflows to complete, then continue
    runs-on: ubuntu-latest
    steps:
      - name: Wait for workflow to complete - Birthdate Check
        uses: lewagon/wait-on-check-action@v1.3.3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: "Restrict Changes"
          # # Run this step twice with a matrix, one for each check you need
          # check-name: ${{ matrix.check }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 5
          allowed-conclusions: success
        # strategy:
        #   matrix:
        #     check:
        #       - "Restrict Changes"
        #       - "Your Other Workflow Name"

  comment:
    runs-on: ubuntu-latest
    needs: wait-for-worklows
    steps:
      - name: Checkout default branch (to get the script)
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 1 # no need for full history

      - name: Run PR status comment script
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          chmod +x .github/workflows/pr-feedback-comment.sh
          .github/workflows/pr-feedback-comment.sh
